# These are supported funding model platforms

github: [srinidh-007]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: srinidh
custom: https://www.buymeacoffee.com/srinidh
